# Generated by Django 4.1.5 on 2023-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
